/**
 * LocalWala - Local Commerce & Delivery Platform
 * (NodeJS, MongoDB, Angular & Flutter)
 *
 * Copyright (c) 2026 WeWorkLocal Private Limited
 * https://weworklocal.in/
 *
 * WeWorkLocal Private Limited
 * This source code is confidential.
 *
 * Ownership Fingerprint:
 * LWL|WWL|2026|LOCALWALA|NODE
 *
 * Phase 3.6: the wallet shared kernel - cash-in-hand ledgers for restaurants and deliverymen, credited on delivery.
 *
 * Pulled out of a business domain because it is cross-cutting, not because the
 * code moved: the boundary rule and the inventory exempt a shared kernel as an
 * import *target*, so the edges that reach it stop being boundary violations.
 * The kernel keeps wallet as its home domain, so the services barrel and
 * the generated facades still publish every name it used to.
 *
 * Published as module bindings, the same shape services/index.js uses. A
 * flattened spread of the members' own functions is not equivalent, and the
 * difference is not academic: two wallet members export identically named
 * functions, so a spread would shadow one set with the other and report
 * nothing.
 *
 * GENERATED by tools/extract-kernel.js - do not hand-edit.
 */
const restaurantCashInHandService = require('./restaurant.cash.in.hand.service.js');
const deliverymanCashInHandService = require('./deliveryman.cash.in.hand.service.js');

module.exports = {
  restaurantCashInHandService,
  deliverymanCashInHandService,
};
