/**
 * LocalWala – Local Commerce & Delivery Platform
 * (NodeJS, MongoDB, Angular & Flutter)
 *
 * Copyright © 2026 WeWorkLocal Private Limited
 * https://weworklocal.in/
 *
 * WeWorkLocal Private Limited
 * This source code is confidential.
 *
 * Ownership Fingerprint:
 * LWL|WWL|2026|LOCALWALA|NODE
 *
 * Phase 3.1 - the notifications domain's public entry point.
 * FCM push, email, chat, conversion tracking.
 *
 * GENERATED by tools/domain-inventory.js --write-domains. Do not edit by
 * hand: `npm run domain:check` fails if this file drifts from the
 * classification in the inventory tool.
 *
 * Re-exports the same names the src/services and src/models barrels
 * export today, so moving a consumer to this file is a one-line change.
 */

import * as chatConversionService from '../../services/chat.conversion.service';
import * as chatRoomService from '../../services/chat.room.service';
import * as emailConfigService from '../../services/email.config.service';
import * as emailTemplatesService from '../../services/email.templates.service';
import * as fcmNotificationService from '../../services/fcm.notification.service';
import * as notificationListService from '../../services/notification.list.service';
import * as pushNotificationTokenService from '../../services/push.notification.token.service';
import * as supportChatConversionService from '../../services/support.chat.conversion.service';
import * as supportChatRoomService from '../../services/support.chat.room.service';
import ChatConversion from '../../models/chat.conversion.model';
import ChatRoom from '../../models/chat.room.model';
import EmailConfig from '../../models/email.config.model';
import EmailTemplate from '../../models/email.templates.model';
import NotificationList from '../../models/notification.list.model';
import PushNotificationToken from '../../models/push.notitication.token.model';
import SupportChatConversion from '../../models/support.chat.conversion.model';
import SupportChatRoom from '../../models/support.chat.room.model';

export { chatConversionService };
export { chatRoomService };
export { emailConfigService };
export { emailTemplatesService };
export { fcmNotificationService };
export { notificationListService };
export { pushNotificationTokenService };
export { supportChatConversionService };
export { supportChatRoomService };
export { ChatConversion };
export { ChatRoom };
export { EmailConfig };
export { EmailTemplate };
export { NotificationList };
export { PushNotificationToken };
export { SupportChatConversion };
export { SupportChatRoom };
