/**
 * LocalWala – Local Commerce & Delivery Platform
 * (NodeJS, MongoDB, Angular & Flutter)
 *
 * Copyright © 2026 WeWorkLocal Private Limited
 * https://weworklocal.in/
 *
 * WeWorkLocal Private Limited
 * This source code is confidential.
 *
 * Ownership Fingerprint:
 * LWL|WWL|2026|LOCALWALA|NODE
 *
 * Phase 3.1 - the catalog domain's public entry point.
 * Menu and catalogue: foods, categories, add-ons, cuisine, taxes.
 *
 * GENERATED by tools/domain-inventory.js --write-domains. Do not edit by
 * hand: `npm run domain:check` fails if this file drifts from the
 * classification in the inventory tool.
 *
 * Re-exports the same names the src/services and src/models barrels
 * export today, so moving a consumer to this file is a one-line change.
 */

import * as addonsService from '../../services/addons.service';
import * as bannersService from '../../services/banners.service';
import * as categoryService from '../../services/category.service';
import * as cuisineService from '../../services/cuisine.service';
import * as foodCampaignRequestService from '../../services/food.campaign.request.service';
import * as foodCampaignService from '../../services/food.campaign.service';
import * as foodService from '../../services/food.service';
import * as foodTaxationService from '../../services/food.taxation.service';
import * as subCategoryService from '../../services/sub.category.service';
import * as vendorCategoryService from '../../services/vendor.category.service';
import * as vendorSubCategoryService from '../../services/vendor.sub.category.service';
import * as foodOrderReviewService from '../../shared/review/food.order.review.service';
import Addons from '../../models/addons.model';
import Banner from '../../models/banners.model';
import Category from '../../models/category.model';
import Coupon from '../../models/coupons.model';
import Cuisine from '../../models/cuisine.model';
import DiningCoupon from '../../models/dining.coupons.model';
import FoodCampaign from '../../models/food.campaign.model';
import FoodCampaignRequest from '../../models/food.campaign.request.model';
import Food from '../../models/food.model';
import FoodOrderReview from '../../models/food.order.review';
import FoodTaxation from '../../models/food.taxation.model';
import SubCategory from '../../models/sub.category.model';
import VendorCategory from '../../models/vendor.category.model';
import VendorSubCategory from '../../models/vendor.sub.category.model';

export { addonsService };
export { bannersService };
export { categoryService };
export { cuisineService };
export { foodCampaignRequestService };
export { foodCampaignService };
export { foodService };
export { foodTaxationService };
export { subCategoryService };
export { vendorCategoryService };
export { vendorSubCategoryService };
export { foodOrderReviewService };
export { Addons };
export { Banner };
export { Category };
export { Coupon };
export { Cuisine };
export { DiningCoupon };
export { FoodCampaign };
export { FoodCampaignRequest };
export { Food };
export { FoodOrderReview };
export { FoodTaxation };
export { SubCategory };
export { VendorCategory };
export { VendorSubCategory };
