/**
 * LocalWala – Local Commerce & Delivery Platform
 * (NodeJS, MongoDB, Angular & Flutter)
 *
 * Copyright © 2026 WeWorkLocal Private Limited
 * https://weworklocal.in/
 *
 * WeWorkLocal Private Limited
 * This source code is confidential.
 *
 * Ownership Fingerprint:
 * LWL|WWL|2026|LOCALWALA|NODE
 *
 * Phase 3.1 - the identity domain's public entry point.
 * Users, auth, roles, tokens, drivers, waiters, support, accountants.
 *
 * GENERATED by tools/domain-inventory.js --write-domains. Do not edit by
 * hand: `npm run domain:check` fails if this file drifts from the
 * classification in the inventory tool.
 *
 * Re-exports the same names the src/services and src/models barrels
 * export today, so moving a consumer to this file is a one-line change.
 */

import * as appWebSettingService from '../../services/app.web.setting.service';
import * as authService from '../../services/auth.service';
import * as cityService from '../../services/city.service';
import * as complaintsReasonService from '../../services/complaints.reason.service';
import * as complaintsService from '../../services/complaints.service';
import * as countryService from '../../services/country.service';
import * as couponService from '../../services/coupon.service';
import * as deliveryGratitudeService from '../../services/delivery.gratitude.service';
import * as deliveryInstructionsService from '../../services/delivery.instructions.service';
import * as diningCouponService from '../../services/dining.coupon.service';
import * as driverIncentiveService from '../../services/driver.incentive.service';
import * as driverOrderReviewService from '../../services/driver.order.review.service';
import * as driverService from '../../services/driver.service';
import * as driverSettingsService from '../../services/driver.settings.service';
import * as favouriteOrderService from '../../services/favourite.order.service';
import * as favouriteService from '../../services/favourite.service';
import * as feedbackFormService from '../../services/feedback.form.service';
import * as guestUserInfoService from '../../services/guest.user.info.service';
import * as languageService from '../../services/language.service';
import * as localityService from '../../services/locality.service';
import * as reportEmergencyFormService from '../../services/report.emergency.form.service';
import * as reportIssueRestaurantReasonService from '../../services/report.issue.restaurant.reason.service';
import * as reportIssueRestaurantService from '../../services/report.issue.restaurant.service';
import * as reviewRatingsService from '../../services/review.ratings.service';
import * as socialSigninService from '../../services/social.signin.service';
import * as tokenService from '../../services/token.service';
import * as userAddressService from '../../services/user.address.service';
import * as userAvatarService from '../../services/user.avatar.service';
import * as userDeleteAccountReasonService from '../../services/user.delete.account.reason.service';
import * as userNotificationSettingService from '../../services/user.notification.setting.service';
import * as userService from '../../services/user.service';
import * as userSettingService from '../../services/user.setting.service';
import * as vehicleService from '../../services/vehicle.service';
import * as visitorService from '../../services/visitor.service';
import * as waiterService from '../../services/waiter.service';
import * as waiterSettingService from '../../services/waiter.setting.service';
import * as otpVerificationService from '../../shared/auth/otp.verification.service';
import City from '../../models/city.model';
import Complaints from '../../models/complaints.model';
import ComplaintsReason from '../../models/complaints.reason.model';
import Country from '../../models/country.model';
import DeletedDeliverymanAccount from '../../models/deleted.deliveryman.account.model';
import DeletedKitchenAccount from '../../models/deleted.kitchen.account.model';
import DeletedRestaurantAccount from '../../models/deleted.restaurant.account.model';
import DeletedUserAccount from '../../models/deleted.user.account.model';
import DeletedWaiterAccount from '../../models/deleted.waiter.account.model';
import DeliveryGratitude from '../../models/delivery.gratitude.model';
import DeliveryInstruction from '../../models/delivery.instructions.model';
import DriverIncentive from '../../models/driver.incentive.model';
import Driver from '../../models/driver.model';
import DriverNewOrderStatus from '../../models/driver.new.order.status.model';
import DriverOrderReview from '../../models/driver.order.review.model';
import DriverSettings from '../../models/driver.settings.model';
import Favourite from '../../models/favourite.model';
import FavouriteOrder from '../../models/favourite.orders.model';
import FeedbackForm from '../../models/feedback.form.model';
import GuestUserInfo from '../../models/guest.user.info.model';
import Language from '../../models/languages.model';
import Locality from '../../models/locality.model';
import OtpVerification from '../../models/otp.verification.model';
import ReportEmergencyForm from '../../models/report.emergency.form.model';
import ReportIssueRestaurant from '../../models/report.issue.restaurant.model';
import ReportIssueRestaurantReason from '../../models/report.issue.restaurant.reason.model';
import SocialSignin from '../../models/social.signin.model';
import Token from '../../models/token.model';
import UserAddress from '../../models/user.address.model';
import UserAvatar from '../../models/user.avatar.model';
import UserDeleteAccountReason from '../../models/user.delete.account.reason.model';
import User from '../../models/user.model';
import UserNotificationSetting from '../../models/user.notification.setting.model';
import UserSettings from '../../models/user.settings.model';
import Vehicle from '../../models/vehicle.model';
import Visitor from '../../models/visitor.model';
import Waiter from '../../models/waiter.model';
import WaiterSettings from '../../models/waiter.settings.model';
import OtpWebVerification from '../../shared/auth/otp.web.verification.model';

export { appWebSettingService };
export { authService };
export { cityService };
export { complaintsReasonService };
export { complaintsService };
export { countryService };
export { couponService };
export { deliveryGratitudeService };
export { deliveryInstructionsService };
export { diningCouponService };
export { driverIncentiveService };
export { driverOrderReviewService };
export { driverService };
export { driverSettingsService };
export { favouriteOrderService };
export { favouriteService };
export { feedbackFormService };
export { guestUserInfoService };
export { languageService };
export { localityService };
export { reportEmergencyFormService };
export { reportIssueRestaurantReasonService };
export { reportIssueRestaurantService };
export { reviewRatingsService };
export { socialSigninService };
export { tokenService };
export { userAddressService };
export { userAvatarService };
export { userDeleteAccountReasonService };
export { userNotificationSettingService };
export { userService };
export { userSettingService };
export { vehicleService };
export { visitorService };
export { waiterService };
export { waiterSettingService };
export { otpVerificationService };
export { City };
export { Complaints };
export { ComplaintsReason };
export { Country };
export { DeletedDeliverymanAccount };
export { DeletedKitchenAccount };
export { DeletedRestaurantAccount };
export { DeletedUserAccount };
export { DeletedWaiterAccount };
export { DeliveryGratitude };
export { DeliveryInstruction };
export { DriverIncentive };
export { Driver };
export { DriverNewOrderStatus };
export { DriverOrderReview };
export { DriverSettings };
export { Favourite };
export { FavouriteOrder };
export { FeedbackForm };
export { GuestUserInfo };
export { Language };
export { Locality };
export { OtpVerification };
export { ReportEmergencyForm };
export { ReportIssueRestaurant };
export { ReportIssueRestaurantReason };
export { SocialSignin };
export { Token };
export { UserAddress };
export { UserAvatar };
export { UserDeleteAccountReason };
export { User };
export { UserNotificationSetting };
export { UserSettings };
export { Vehicle };
export { Visitor };
export { Waiter };
export { WaiterSettings };
export { OtpWebVerification };
