/**
 * LocalWala – Local Commerce & Delivery Platform
 * (NodeJS, MongoDB, Angular & Flutter)
 *
 * Copyright © 2026 WeWorkLocal Private Limited
 * https://weworklocal.in/
 *
 * WeWorkLocal Private Limited
 *
 * This source code is confidential.
 * Unauthorized copying, redistribution, resale, publication,
 * modification, or use of this source code in any public or
 * commercial repository is strictly prohibited.
 *
 * Ownership Fingerprint:
 * LWL|WWL|2026|LOCALWALA|NODE
 */

const citySchemaArray = ['name', 'latitude', 'longitude', 'image', 'status'];
const localitySchemaArray = ['name', 'city', 'latitude', 'longitude', 'status'];
const cuisineSchemaArray = ['name', 'image', 'status'];
const orderCancelReasonSchemaArray = ['name', 'type', 'status'];
const orderRatingMessageSchemaArray = ['name', 'rateNumber', 'type', 'status'];
const invoiceInstructionSchemaArray = ['name', 'status'];
const restaurantFoodLicenseSchemaArray = ['name', 'website', 'image', 'status'];
const restaurantNoticeSchemaArray = ['name', 'status'];
const deliveryInstructionSchemaArray = ['name', 'image', 'status'];
const deliveryGratitudeSchemaArray = ['price', 'mostTipped', 'status'];
const deliveryIncentiveSchemaArray = ['orderTotal', 'incentiveAmount', 'status'];
const driverOfflineMessageSchemaArray = ['name', 'status'];
const userDeleteAccountReasonSchemaArray = ['name', 'kind', 'status'];
const diningCategorySchemaArray = ['name', 'image', 'status'];
const diningCancellationSchemaArray = ['name', 'type', 'status'];
const diningInstructionSchemaArray = ['name', 'status'];
const languageSchemaArray = [
  'name',
  'nativeName',
  'code',
  'direction',
  'image',
  'isDefault',
  'status',
];
const userAvatarSchemaArray = ['avatar', 'isDefault', 'status'];
const subscriptionPackageSchemaArray = [
  'name',
  'price',
  'discount',
  'shortDescriptions',
  'validity',
  'haveTrial',
  'trialValidity',
  'icon',
  'pos',
  'ownDriver',
  'promote',
  'customCategory',
  'multiOutlet',
  'preBooking',
  'tableOrder',
  'tiffinSubscription',
  'ownWaiter',
  'ownKitchen',
  'orderLimit',
  'productLimit',
  'commission',
  'status',
];
const restaurantSubscriberSchemaArray = [
  'restaurant',
  'subscriptions',
  'trialStartDate',
  'trialEndDate',
  'startDate',
  'endDate',
  'status',
];
const restaurantReportIssueSchemaArray = ['user', 'restaurant', 'reason', 'message', 'status'];
const reportIssueReasonSchemaArray = ['name', 'status'];
const customerSchemaArray = [
  'firstName',
  'lastName',
  'email',
  'role',
  'image',
  'countryCode',
  'mobile',
  'gender',
  'latitude',
  'longitude',
  'city',
  'locale',
  'status',
];
const loyalityPointSchemaArray = [
  'user',
  'orderId',
  'coupon',
  'loyaltyPointValue',
  'redeemFrom',
  'redeemedToWallet',
];
const hiddenRestaurantSchemaArray = ['user', 'restaurant', 'reason'];
const hiddentRestaurantReasonSchemaArray = ['name', 'status'];
const restaurantTypeSchemaArray = ['name', 'image', 'status'];
const restaurantFacilitiesSchemaArray = ['name', 'status'];
const vehicleSchemaArray = ['name', 'extraCharge', 'minimumCoverage', 'maximumCoverage', 'status'];
const shiftScheduleSchemaArray = [
  'name',
  'startTime',
  'endTime',
  'extraEarningPercentage',
  'status',
];
const authRoleSchemaArray = [
  'firstName',
  'lastName',
  'email',
  'image',
  'countryCode',
  'mobile',
  'gender',
  'city',
  'status',
];
const customerWalletFundSchemaArray = ['userId', 'walletId', 'amount', 'notes'];
const walletBonusSchemaArray = [
  'name',
  'shortDescription',
  'image',
  'start',
  'expires',
  'bonusType',
  'bonusAmount',
  'minWalletAmount',
  'maxBonusAmount',
  'status',
];
const orderRefundReasonSchemaArray = ['name', 'status'];
const tiffinRefundReasonSchemaArray = ['name', 'status'];
const diningBookingRefundReasonSchemaArray = ['name', 'status'];
const complaintReasonSchemaArray = ['name', 'type', 'status'];
const mediaFileSchemaArray = ['user', 'path'];
const foodAddonSchemaArray = [
  'name',
  'price',
  'restaurant',
  'inStock',
  'stockType',
  'stockNumber',
  'status',
];
const foodCategorySchemaArray = ['name', 'image', 'status'];
const foodSubCategorySchemaArray = ['name', 'category', 'status'];
const foodTaxationSchemaArray = ['restaurant', 'taxName', 'taxAmount'];
const tiffinSubscriptionCancellationReasonSchemaArray = ['name', 'type', 'status'];
const cashCollectionSchemaArray = [
  'from',
  'deliveryman',
  'restaurant',
  'cashCollected',
  'walletAmount',
  'method',
  'reference',
];
const bannerSchemaArray = [
  'title',
  'type',
  'city',
  'restaurant',
  'food',
  'external',
  'image',
  'status',
];
const deliverymanWalletFundSchemaArray = ['driverUID', 'walletId', 'amount', 'notes'];
const systemDeliverymanSchemaArray = [
  'firstName',
  'lastName',
  'email',
  'image',
  'countryCode',
  'mobile',
  'gender',
  'latitude',
  'longitude',
  'city',
  'locality',
  'vehicle',
  'type',
  'identity',
  'identityNumber',
  'identityProof',
  'drivingLicense',
  'age',
  'dob',
  'isBlocked',
  'offlineReason',
  'status',
];
const vendorDeliverymanSchemaArray = [
  'firstName',
  'lastName',
  'email',
  'image',
  'countryCode',
  'mobile',
  'gender',
  'restaurant',
  'latitude',
  'longitude',
  'city',
  'locality',
  'vehicle',
  'identity',
  'identityNumber',
  'identityProof',
  'drivingLicense',
  'age',
  'dob',
  'isBlocked',
  'offlineReason',
  'status',
];
const restaurantWaiterSchemaArray = [
  'firstName',
  'lastName',
  'email',
  'image',
  'countryCode',
  'mobile',
  'gender',
  'city',
  'restaurant',
  'status',
];
const restaurantKitchenOwnerSchemaArray = [
  'firstName',
  'lastName',
  'email',
  'image',
  'countryCode',
  'mobile',
  'gender',
  'city',
  'restaurant',
  'status',
];
const restaurantSchemaArray = [
  'firstName',
  'lastName',
  'email',
  'image',
  'countryCode',
  'mobile',
  'gender',
  'latitude',
  'longitude',
  'name',
  'address',
  'shortDescription',
  'cuisine',
  'diningCategory',
  'logo',
  'cover',
  'city',
  'locality',
  'type',
  'commission',
  'posOrderCommission',
  'tableOrderCommission',
  'subscription',
  'approxDeliveryTime',
  'dishPriceForTwo',
  'pos',
  'ownDriver',
  'promote',
  'customCategory',
  'multiOutlet',
  'preBooking',
  'tableOrder',
  'tiffinSubscription',
  'ownWaiter',
  'ownKitchen',
  'takeAway',
  'slots',
  'orderLimit',
  'productLimit',
  'restaurantType',
  'restaurantFacility',
  'temporaryClosed',
  'acceptScheduleDelivery',
  'acceptHomeDelivery',
  'minOrderAmount',
  'license',
  'licenseId',
  'socialFacebook',
  'socialInstagram',
  'socialX',
  'socialYoutube',
  'socialLinkedIn',
  'socialPinterest',
  'status',
];
const restaurantOutletSchemaArray = [
  'firstName',
  'lastName',
  'email',
  'image',
  'countryCode',
  'mobile',
  'gender',
  'latitude',
  'longitude',
  'outletRestaurantId',
  'name',
  'address',
  'shortDescription',
  'cuisine',
  'diningCategory',
  'logo',
  'cover',
  'city',
  'locality',
  'approxDeliveryTime',
  'dishPriceForTwo',
  'takeAway',
  'slots',
  'orderLimit',
  'productLimit',
  'restaurantType',
  'restaurantFacility',
  'temporaryClosed',
  'acceptScheduleDelivery',
  'acceptHomeDelivery',
  'minOrderAmount',
  'license',
  'licenseId',
  'socialFacebook',
  'socialInstagram',
  'socialX',
  'socialYoutube',
  'socialLinkedIn',
  'socialPinterest',
  'status',
];
const regularChatListSchemaArray = ['senderId', 'receiverId', 'lastMessage', 'lastMessageType'];
const regularChatMessageSchemaArray = ['roomId', 'senderId', 'message', 'messageType'];
const supportChatListSchemaArray = [
  'userId',
  'supportTeam',
  'orders',
  'booking',
  'purchaseSubscription',
  'complaints',
  'reportIssue',
  'restaurantComplaints',
  'supportType',
  'lastMessage',
  'lastMessageType',
  'resolvedBy',
  'status',
];
const supportChatMessageSchemaArray = ['roomId', 'senderId', 'message', 'messageType'];
const customerComplaintSchemaArray = [
  'user',
  'orders',
  'reason',
  'title',
  'brief',
  'issueWith',
  'restaurant',
  'driver',
  'product',
  'proof',
  'status',
];
const restaurantComplaintSchemaArray = [
  'restaurant',
  'orders',
  'reason',
  'title',
  'brief',
  'issueWith',
  'driver',
  'customer',
  'proof',
  'status',
];
const adminExpenseSchemaArray = [
  'expenseType',
  'coupon',
  'diningCoupon',
  'diningBooking',
  'order',
  'user',
  'amount',
];
const walletTransactionSchemaArray = [
  'userId',
  'walletId',
  'type',
  'amount',
  'uuid',
  'confirmed',
  'notes',
  'status',
];
const paymentTransactionSchemaArray = [
  'user',
  'payment',
  'orders',
  'tiffinSubscription',
  'booking',
  'restaurantRegisterRequest',
  'subscribeId',
  'amount',
  'paymentFrom',
  'paymentRef',
  'payResponse',
  'status',
];
const regularOrderRefundSchemaArray = [
  'user',
  'orders',
  'restaurant',
  'payment',
  'amount',
  'refundTo',
  'payResponse',
  'refundReason',
  'cancelReason',
  'status',
];
const tiffinRefundSchemaArray = [
  'user',
  'purchaseSubscription',
  'subscriptionPackage',
  'restaurant',
  'payment',
  'amount',
  'refundTo',
  'payResponse',
  'refundReason',
  'cancelReason',
  'status',
];
const diningBookingRefundSchemaArray = [
  'user',
  'booking',
  'restaurant',
  'payment',
  'amount',
  'refundTo',
  'payResponse',
  'refundReason',
  'cancelReason',
  'status',
];
const orderCouponSchemaArray = [
  'name',
  'city',
  'latitude',
  'longitude',
  'couponType',
  'allRestaurants',
  'restaurant',
  'allUsers',
  'user',
  'code',
  'limitSameUser',
  'start',
  'expires',
  'discountType',
  'minDiscount',
  'maxDiscount',
  'minCartTotal',
  'loyalityPoints',
  'status',
];
const diningBookingCouponSchemaArray = [
  'name',
  'city',
  'latitude',
  'longitude',
  'allRestaurants',
  'restaurant',
  'allUsers',
  'user',
  'code',
  'limitSameUser',
  'start',
  'expires',
  'discountType',
  'minDiscount',
  'maxDiscount',
  'availability',
  'preBookingChargeRequired',
  'preBookingChargeAmount',
  'status',
];
const restaurantCampaignSchemaArray = [
  'title',
  'shortDescription',
  'city',
  'restaurant',
  'image',
  'startDate',
  'endDate',
  'startTime',
  'endTime',
  'status',
];
const diningCampaignSchemaArray = [
  'title',
  'shortDescription',
  'city',
  'restaurant',
  'image',
  'startDate',
  'endDate',
  'startTime',
  'endTime',
  'status',
];
const foodCampaignSchemaArray = [
  'title',
  'shortDescription',
  'city',
  'foods',
  'image',
  'startDate',
  'endDate',
  'startTime',
  'endTime',
  'status',
];
const diningBookingSchemaArray = [
  'user',
  'payment',
  'paymentMode',
  'restaurant',
  'coupon',
  'campaign',
  'bookingDate',
  'bookingSlot',
  'guest',
  'userName',
  'userCountryCode',
  'userContact',
  'userEmail',
  'specialRequest',
  'preBookingCharge',
  'couponCoverCharge',
  'grandTotal',
  'bookingCancellation',
  'bookingCommission',
  'diningItemTotalAmount',
  'diningItemDiscountAmount',
  'diningCouponDiscountAmount',
  'diningGrandTotalBillAmount',
  'status',
];
const withdrawalMethodSchemaArray = ['name', 'image', 'formElement', 'isDefault', 'status'];
const tiffinSubscriptionPackageSchemaArray = [
  'name',
  'shortDescription',
  'image',
  'restaurant',
  'foods',
  'interval',
  'offDays',
  'totalOrder',
  'orderTo',
  'deliveryArea',
  'available',
  'timeSlots',
  'canSelectAddon',
  'canSelectVariation',
  'price',
  'discountType',
  'discount',
  'notice',
  'status',
];
const tiffinSubscriptionPurchasedSchemaArray = [
  'user',
  'subscriptionPackage',
  'payment',
  'restaurant',
  'addons',
  'foods',
  'slot',
  'orderAt',
  'orderTo',
  'cookingInstruction',
  'deliveryInstruction',
  'deliveryAddress',
  'deliveryAddressRaw',
  'receiverName',
  'countryCode',
  'receiverContact',
  'cartItemRaw',
  'itemTotal',
  'foodServiceCharge',
  'serviceCharge',
  'packageCharge',
  'packageChargeTax',
  'extraCharge',
  'grandTotal',
  'totalOrder',
  'startDate',
  'offDays',
  'ordersDates',
  'requestedOffDates',
  'subscriptionCancellation',
  'cancellationBy',
  'status',
];
const foodSchemaArray = [
  'name',
  'shortDescription',
  'image',
  'restaurant',
  'ownCategory',
  'category',
  'subCategory',
  'customCategory',
  'customSubCategory',
  'foodType',
  'addons',
  'startTime',
  'endTime',
  'price',
  'discountType',
  'discount',
  'purchaseLimit',
  'variations',
  'tags',
  'recommended',
  'rating',
  'inStock',
  'stockType',
  'stockNumber',
  'taxationEnable',
  'foodTax',
  'orderSoldCount',
  'totalSoldAmount',
  'discountAmountGiven',
  'status',
];
const regularOrderSchemaArray = [
  'orderNo',
  'user',
  'driver',
  'payment',
  'paymentMode',
  'restaurant',
  'addons',
  'foods',
  'coupon',
  'couponType',
  'orderTo',
  'cookingInstruction',
  'deliveryInstruction',
  'deliveryAddress',
  'deliveryAddressRaw',
  'receiverName',
  'countryCode',
  'receiverContact',
  'cartItemRaw',
  'walletUsed',
  'instantOrder',
  'scheduleOrder',
  'scheduleDate',
  'orderAt',
  'scheduleTime',
  'realTotal',
  'itemTotal',
  'itemDiscount',
  'couponDiscountCharge',
  'deliveryCharge',
  'foodServiceCharge',
  'serviceCharge',
  'packageCharge',
  'packageChargeTax',
  'deliveryTip',
  'extraCharge',
  'walletAmount',
  'grandTotal',
  'preparationTime',
  'userOrderCount',
  'driverOrderPin',
  'customerOrderPin',
  'orderCancellation',
  'cancellationBy',
  'driverAssign',
  'orderFrom',
  'ratingSaved',
  'subscriptionOrder',
  'purchasedTiffinSubscription',
  'tiffinSubscription',
  'restaurantCampaign',
  'foodCampaign',
  'refundedAmount',
  'driverEarining',
  'deliveryCommission',
  'restaurantCommission',
  'status',
];
const vendorPOSOrderSchemaArray = [
  'orderNo',
  'foods',
  'restaurant',
  'paymentMode',
  'customerType',
  'customerName',
  'customerCountryCode',
  'customerMobileNumber',
  'cartItemRaw',
  'realTotal',
  'itemTotal',
  'itemDiscount',
  'discountType',
  'discountAmount',
  'discountCharge',
  'foodServiceCharge',
  'serviceCharge',
  'packageCharge',
  'packageChargeTax',
  'waiterTip',
  'extraCharge',
  'grandTotal',
  'orderFrom',
  'restaurantCommission',
  'status',
];
const vendorTableOrderSchameArray = [
  'orderNo',
  'tableNo',
  'foods',
  'waiters',
  'restaurant',
  'paymentMode',
  'customerType',
  'customerName',
  'customerCountryCode',
  'customerMobileNumber',
  'cartItemRaw',
  'realTotal',
  'itemTotal',
  'itemDiscount',
  'discountType',
  'discountAmount',
  'discountCharge',
  'foodServiceCharge',
  'serviceCharge',
  'packageCharge',
  'packageChargeTax',
  'waiterTip',
  'extraCharge',
  'grandTotal',
  'restaurantCommission',
];

module.exports = {
  citySchemaKeys: citySchemaArray,
  localitySchemaKeys: localitySchemaArray,
  cuisineSchemaKeys: cuisineSchemaArray,
  orderCancelReasonSchemaKeys: orderCancelReasonSchemaArray,
  orderRatingMessageSchemaKeys: orderRatingMessageSchemaArray,
  invoiceInstructionSchemaKeys: invoiceInstructionSchemaArray,
  restaurantFoodLicenseSchemaKeys: restaurantFoodLicenseSchemaArray,
  restaurantNoticeSchemaKeys: restaurantNoticeSchemaArray,
  deliveryInstructionSchemaKeys: deliveryInstructionSchemaArray,
  deliveryGratitudeSchemaKeys: deliveryGratitudeSchemaArray,
  deliveryIncentiveSchemaKeys: deliveryIncentiveSchemaArray,
  driverOfflineMessageSchemaKeys: driverOfflineMessageSchemaArray,
  userDeleteAccountReasonSchemaKeys: userDeleteAccountReasonSchemaArray,
  diningCategorySchemaKeys: diningCategorySchemaArray,
  diningCancellationSchemaKeys: diningCancellationSchemaArray,
  diningInstructionSchemaKeys: diningInstructionSchemaArray,
  languageSchemaKeys: languageSchemaArray,
  userAvatarSchemaKeys: userAvatarSchemaArray,
  subscriptionPackageSchemaKeys: subscriptionPackageSchemaArray,
  restaurantSubscriberSchemaKey: restaurantSubscriberSchemaArray,
  restaurantReportIssueSchemaKeys: restaurantReportIssueSchemaArray,
  reportIssueReasonSchemaKeys: reportIssueReasonSchemaArray,
  customerSchemaKeys: customerSchemaArray,
  loyalityPointSchemaKeys: loyalityPointSchemaArray,
  hiddenRestaurantSchemaKeys: hiddenRestaurantSchemaArray,
  hiddentRestaurantReasonSchemaKeys: hiddentRestaurantReasonSchemaArray,
  restaurantTypeSchemaKeys: restaurantTypeSchemaArray,
  restaurantFacilitiesSchemaKeys: restaurantFacilitiesSchemaArray,
  vehicleSchemaKeys: vehicleSchemaArray,
  shiftScheduleSchemaKeys: shiftScheduleSchemaArray,
  authRoleSchemaKeys: authRoleSchemaArray,
  customerWalletFundSchemaKeys: customerWalletFundSchemaArray,
  walletBonusSchemaKeys: walletBonusSchemaArray,
  orderRefundReasonSchemaKeys: orderRefundReasonSchemaArray,
  tiffinRefundReasonSchemaKeys: tiffinRefundReasonSchemaArray,
  diningBookingRefundReasonSchemaKeys: diningBookingRefundReasonSchemaArray,
  complaintReasonSchemaKeys: complaintReasonSchemaArray,
  mediaFileSchemaKeys: mediaFileSchemaArray,
  foodAddonSchemaKeys: foodAddonSchemaArray,
  foodCategorySchemaKeys: foodCategorySchemaArray,
  foodSubCategorySchemaKeys: foodSubCategorySchemaArray,
  foodTaxationSchemaKeys: foodTaxationSchemaArray,
  tiffinSubscriptionCancellationReasonSchemaKeys: tiffinSubscriptionCancellationReasonSchemaArray,
  cashCollectionSchemaKeys: cashCollectionSchemaArray,
  bannerSchemaKeys: bannerSchemaArray,
  deliverymanWalletFundSchemaKeys: deliverymanWalletFundSchemaArray,
  systemDeliverymanSchemaKeys: systemDeliverymanSchemaArray,
  vendorDeliverymanSchemaKeys: vendorDeliverymanSchemaArray,
  restaurantWaiterSchemaKeys: restaurantWaiterSchemaArray,
  restaurantKitchenOwnerSchemaKeys: restaurantKitchenOwnerSchemaArray,
  restaurantSchemaKeys: restaurantSchemaArray,
  restaurantOutletSchemaKeys: restaurantOutletSchemaArray,
  regularChatListSchemaKeys: regularChatListSchemaArray,
  regularChatMessageSchemaKeys: regularChatMessageSchemaArray,
  supportChatListSchemaKeys: supportChatListSchemaArray,
  supportChatMessageSchemaKeys: supportChatMessageSchemaArray,
  customerComplaintSchemaKeys: customerComplaintSchemaArray,
  restaurantComplaintSchemaKeys: restaurantComplaintSchemaArray,
  adminExpenseSchemaKeys: adminExpenseSchemaArray,
  walletTransactionSchemaKeys: walletTransactionSchemaArray,
  paymentTransactionSchemaKeys: paymentTransactionSchemaArray,
  regularOrderRefundSchemaKeys: regularOrderRefundSchemaArray,
  tiffinRefundSchemaKeys: tiffinRefundSchemaArray,
  diningBookingRefundSchemaKeys: diningBookingRefundSchemaArray,
  orderCouponSchemaKeys: orderCouponSchemaArray,
  diningBookingCouponSchemaKeys: diningBookingCouponSchemaArray,
  restaurantCampaignSchemaKeys: restaurantCampaignSchemaArray,
  diningCampaignSchemaKeys: diningCampaignSchemaArray,
  foodCampaignSchemaKeys: foodCampaignSchemaArray,
  diningBookingSchemaKeys: diningBookingSchemaArray,
  withdrawalMethodSchemaKeys: withdrawalMethodSchemaArray,
  tiffinSubscriptionPackageSchemaKeys: tiffinSubscriptionPackageSchemaArray,
  tiffinSubscriptionPurchasedSchemaKeys: tiffinSubscriptionPurchasedSchemaArray,
  foodSchemaKeys: foodSchemaArray,
  regularOrderSchemakeys: regularOrderSchemaArray,
  vendorPOSOrderSchemaKeys: vendorPOSOrderSchemaArray,
  vendorTableOrderSchameKeys: vendorTableOrderSchameArray,
};

