/**
 * LocalWala – Local Commerce & Delivery Platform
 * (NodeJS, MongoDB, Angular & Flutter)
 *
 * Copyright © 2026 WeWorkLocal Private Limited
 * https://weworklocal.in/
 *
 * WeWorkLocal Private Limited
 *
 * This source code is confidential.
 * Unauthorized copying, redistribution, resale, publication,
 * modification, or use of this source code in any public or
 * commercial repository is strictly prohibited.
 *
 * Ownership Fingerprint:
 * LWL|WWL|2026|LOCALWALA|NODE
 */

const apiLocaleTranslations = {
  en: {
    direction: 'ltr',
    orderSummary: {
      orderSummaryKey: 'Order Summary',
      orderIdKey: 'Order ID',
      orderTimeKey: 'Order Time',
      customerNameKey: 'Customer Name',
      deliveryAddressKey: 'Delivery Address',
      restaurantNameKey: 'Restaurant Name',
      restaurantAddressKey: 'Restaurant Address',
      driverNameKey: "Delivery partner's Name",
      itemKey: 'Item',
      quantityKey: 'Quantity',
      unitPriceKey: 'Unit Price',
      totalPriceKey: 'Total Price',
      itemTotalKey: 'Item Total',
      foodServiceChargeKey: 'Food Service Charge',
      serviceChargeKey: 'Service Charge',
      deliveryChargeKey: 'Delivery Charge',
      deliveryTipKey: 'Delivery Tip',
      packageChargeKey: 'Packaging Charge',
      packageChargeTaxKey: 'Packaging Charge Tax',
      extraChargeKey: 'Extra Charge',
      discountChargeKey: 'Discount Amount',
      walletChargeKey: 'Wallet Amount',
      grandTotalKey: 'Grand Total',
      licenseKey: 'Lic. No.',
      selfPickupKey: 'Self Pickup',
    },
    orderInvoice: {
      orderInvoiceKey: 'Order Invoice',
      taxInvoiceKey: 'Tax Invoice',
      digitalCopyKey: 'Digital Copy For Recipient',
      taxBehalfKey: 'Tax Invoice on behalf of -',
      legalNameKey: 'Legal Entity Name',
      restaurantNameKey: 'Restaurant Name',
      restaurantAddressKey: 'Restaurant Address',
      restaurantLicenseKey: 'Restaurant License',
      invoiceNumberKey: 'Invoice No.',
      invoiceDateKey: 'Invoice Date',
      customerNameKey: 'Customer Name',
      deliveryAddressKey: 'Delivery Address',
      serviceDescriptionKey: 'Service Description',
      serviceDescriptionValue: 'Restaurant Service',
      itemKey: 'Items',
      grossValueKey: 'Gross Value',
      discountKey: 'Discount',
      netValueKey: 'Net Value',
      taxNameKey: 'Tax Name',
      taxValueKey: 'Tax Value',
      totalKey: 'Total',
      itemTotalKey: 'Item(s) Total',
      foodServiceChargeKey: 'Food Service Charge',
      serviceChargeKey: 'Service Charge',
      deliveryChargeKey: 'Delivery Charge',
      deliveryTipKey: 'Delivery Tip',
      restaurantPackagingChargeKey: 'Restaurant Packaging Charge',
      extraChargeKey: 'Extra Charge',
      couponDiscountKey: 'Coupon Discount',
      walletDiscountKey: 'Wallet Discount',
      totalValueKey: 'Total Value',
      amountKey: 'Amount',
      onlinePayDescriptionKey:
        'settled through digital payment received upon delivery against Order ID',
      offlinePayDescriptionKey:
        'settled through cash payment received upon delivery against Order ID',
      licenseKey: 'Lic.',
    },
    bookingSummary: {
      bookingSummaryKey: 'Dining Booking Summary',
      bookingIdKey: 'Booking Id',
      bookingDateTimeKey: 'Scheduled',
      guestCountKey: 'Number of guests',
      customerNameKey: 'Customer Name',
      customerEmailKey: 'Email',
      customerPhoneKey: 'Phone',
      restaurantNameKey: 'Restaurant Name',
      restaurantAddressKey: 'Restaurant Address',
      licenseKey: 'Lic. No.',
    },
    bookingInvoice: {
      bookingInvoiceKey: 'Dining Booking Invoice',
      taxInvoiceKey: 'Tax Invoice',
      digitalCopyKey: 'Digital Copy For Recipient',
      taxBehalfKey: 'Tax Invoice on behalf of -',
      legalNameKey: 'Legal Entity Name',
      restaurantNameKey: 'Restaurant Name',
      restaurantAddressKey: 'Restaurant Address',
      restaurantLicenseKey: 'Restaurant License',
      invoiceNumberKey: 'Invoice No.',
      invoiceDateKey: 'Invoice Date',
      customerNameKey: 'Customer Name',
      serviceDescriptionKey: 'Service Description',
      serviceDescriptionValue: 'Restaurant Service',
      onlinePayDescriptionKey:
        'settled through digital payment received upon delivery against Booking ID',
      offlinePayDescriptionKey:
        'settled through cash payment received upon delivery against Booking ID',
      licenseKey: 'Lic.',
      customerEmailKey: 'Customer Email',
      customerPhoneKey: 'Customer Contact No',
      preBookingChargeKey: 'Pre Booking Charge',
      couponCoverChargeKey: 'Coupon Cover Charge',
      grandTotalKey: 'Amount Paid',
      diningItemTotalAmountKey: 'Item Total',
      diningItemDiscountAmountKey: 'Item Discount',
      diningCouponDiscountAmountKey: 'Coupon Discount',
      diningGrandTotalBillAmountKey: 'Billing Total',
    },
    tiffinSubscriptionSummary: {
      purchasedSummaryKey: 'Tiffin Subscription Purchase Summary',
      purchasedIdKey: 'Purchased ID',
      purchasedTimeKey: 'Purchased Time',
      customerNameKey: 'Customer Name',
      deliveryAddressKey: 'Delivery Address',
      restaurantNameKey: 'Restaurant Name',
      restaurantAddressKey: 'Restaurant Address',
      itemKey: 'Item',
      quantityKey: 'Quantity',
      unitPriceKey: 'Unit Price',
      totalPriceKey: 'Total Price',
      itemTotalKey: 'Item Total',
      foodServiceChargeKey: 'Food Service Charge',
      serviceChargeKey: 'Service Charge',
      packageChargeKey: 'Packaging Charge',
      packageChargeTaxKey: 'Packaging Charge Tax',
      extraChargeKey: 'Extra Charge',
      grandTotalKey: 'Grand Total',
      licenseKey: 'Lic. No.',
      packageNameKey: 'Package Name',
      totalOrderKey: 'Total Orders',
      breakfast: 'Breakfast',
      lunch: 'Lunch',
      dinner: 'Dinner',
    },
    tiffinSubscriptionInvoice: {
      purchaseInvoiceKey: 'Tiffin Subscription Purchase Invoice',
      taxInvoiceKey: 'Tax Invoice',
      digitalCopyKey: 'Digital Copy For Recipient',
      taxBehalfKey: 'Tax Invoice on behalf of -',
      legalNameKey: 'Legal Entity Name',
      restaurantNameKey: 'Restaurant Name',
      restaurantAddressKey: 'Restaurant Address',
      restaurantLicenseKey: 'Restaurant License',
      invoiceNumberKey: 'Invoice No.',
      invoiceDateKey: 'Invoice Date',
      customerNameKey: 'Customer Name',
      deliveryAddressKey: 'Delivery Address',
      serviceDescriptionKey: 'Service Description',
      serviceDescriptionValue: 'Restaurant Service',
      itemKey: 'Items',
      grossValueKey: 'Gross Value',
      discountKey: 'Discount',
      netValueKey: 'Net Value',
      taxNameKey: 'Tax Name',
      taxValueKey: 'Tax Value',
      totalKey: 'Total',
      itemTotalKey: 'Item(s) Total',
      foodServiceChargeKey: 'Food Service Charge',
      serviceChargeKey: 'Service Charge',
      restaurantPackagingChargeKey: 'Restaurant Packaging Charge',
      extraChargeKey: 'Extra Charge',
      totalValueKey: 'Total Value',
      amountKey: 'Amount',
      onlinePayDescriptionKey:
        'settled through digital payment received upon delivery against Purchase ID',
      offlinePayDescriptionKey:
        'settled through cash payment received upon delivery against Purchase ID',
      licenseKey: 'Lic.',
      packageNameKey: 'Package Name',
      totalOrderKey: 'Total Orders',
      breakfast: 'Breakfast',
      lunch: 'Lunch',
      dinner: 'Dinner',
    },
  },
  hi: {
    direction: 'ltr',
    orderSummary: {
      orderSummaryKey: 'आदेश सारांश',
      orderIdKey: 'आदेश कामतत्व',
      orderTimeKey: 'ऑर्डर का समय',
      customerNameKey: 'ग्राहक का नाम',
      deliveryAddressKey: 'डिलीवरी पता',
      restaurantNameKey: 'रेस्तरां का नाम',
      restaurantAddressKey: 'रेस्तरां का पता',
      driverNameKey: 'डिलीवरी पार्टनर का नाम',
      itemKey: 'आइटम',
      quantityKey: 'मात्रा',
      unitPriceKey: 'यूनिट मूल्य',
      totalPriceKey: 'कुल मूल्य',
      itemTotalKey: 'आइटम कुल',
      foodServiceChargeKey: 'खाद्य सेवा शुल्क',
      serviceChargeKey: 'सेवा शुल्क',
      deliveryChargeKey: 'डिलीवरी शुल्क',
      deliveryTipKey: 'डिलीवरी टिप',
      packageChargeKey: 'पैकेजिंग शुल्क',
      packageChargeTaxKey: 'पैकेजिंग शुल्क कर',
      extraChargeKey: 'अतिरिक्त शुल्क',
      discountChargeKey: 'छूट राशि',
      walletChargeKey: 'वॉलेट राशि',
      grandTotalKey: 'कुल राशि',
      licenseKey: 'लाइसेंस संख्या',
      selfPickupKey: 'स्व चयन',
    },
    orderInvoice: {
      orderInvoiceKey: 'ऑर्डर इनवॉइस',
      taxInvoiceKey: 'टैक्स इनवॉइस',
      digitalCopyKey: 'प्राप्तकर्ता के लिए डिजिटल कॉपी',
      taxBehalfKey: '- की ओर से टैक्स इनवॉइस',
      legalNameKey: 'कानूनी इकाई का नाम',
      restaurantNameKey: 'रेस्तरां का नाम',
      restaurantAddressKey: 'रेस्तरां का पता',
      restaurantLicenseKey: 'रेस्तरां का लाइसेंस',
      invoiceNumberKey: 'इनवॉइस नंबर.',
      invoiceDateKey: 'इनवॉइस की तारीख',
      customerNameKey: 'ग्राहक का नाम',
      deliveryAddressKey: 'डिलीवरी पता',
      serviceDescriptionKey: 'सेवा विवरण',
      serviceDescriptionValue: 'रेस्तरां सेवा',
      itemKey: 'आइटम',
      grossValueKey: 'ग्रॉस वैल्यू',
      discountKey: 'छूट',
      netValueKey: 'नेट वैल्यू',
      taxNameKey: 'टैक्स का नाम',
      taxValueKey: 'टैक्स वैल्यू',
      totalKey: 'टोटल',
      itemTotalKey: 'आइटम टोटल',
      foodServiceChargeKey: 'फूड सर्विस चार्ज',
      serviceChargeKey: 'सर्विस चार्ज',
      deliveryChargeKey: 'डिलीवरी चार्ज',
      deliveryTipKey: 'डिलीवरी टिप',
      restaurantPackagingChargeKey: 'रेस्तरां पैकेजिंग चार्ज',
      extraChargeKey: 'अतिरिक्त चार्ज',
      couponDiscountKey: 'कूपन डिस्काउंट',
      walletDiscountKey: 'वॉलेट डिस्काउंट',
      totalValueKey: 'टोटल वैल्यू',
      amountKey: 'अमाउंट',
      onlinePayDescriptionKey:
        'ऑर्डर आईडी के खिलाफ डिलीवरी पर प्राप्त डिजिटल भुगतान के माध्यम से निपटारा',
      offlinePayDescriptionKey:
        'ऑर्डर आईडी के विरुद्ध डिलीवरी पर प्राप्त नकद भुगतान के माध्यम से निपटाया गया',
      licenseKey: 'लाइसेंस.',
    },
    bookingSummary: {
      bookingSummaryKey: 'भोजन बुकिंग सारांश',
      bookingIdKey: 'बुकिंग आईडी',
      bookingDateTimeKey: 'निर्धारित',
      guestCountKey: 'मेहमानों की संख्या',
      customerNameKey: 'ग्राहक का नाम',
      customerEmailKey: 'ईमेल',
      customerPhoneKey: 'फोन',
      restaurantNameKey: 'रेस्तरां का नाम',
      restaurantAddressKey: 'रेस्तरां का पता',
      licenseKey: 'लाइसेंस संख्या',
    },
    bookingInvoice: {
      bookingInvoiceKey: 'डाइनिंग बुकिंग चालान',
      taxInvoiceKey: 'कर चालान',
      digitalCopyKey: 'प्राप्तकर्ता के लिए डिजिटल प्रति',
      taxBehalfKey: 'की ओर से कर चालान -',
      legalNameKey: 'कानूनी इकाई का नाम',
      restaurantNameKey: 'रेस्तरां का नाम',
      restaurantAddressKey: 'रेस्तरां का पता',
      restaurantLicenseKey: 'रेस्तरां लाइसेंस',
      invoiceNumberKey: 'चालान संख्या',
      invoiceDateKey: 'चालान तिथि',
      customerNameKey: 'ग्राहक का नाम',
      serviceDescriptionKey: 'सेवा विवरण',
      serviceDescriptionValue: 'रेस्तरां सेवा',
      onlinePayDescriptionKey:
        'आरक्षण आईडी के विरुद्ध डिलीवरी पर प्राप्त डिजिटल भुगतान के माध्यम से निपटान किया गया',
      offlinePayDescriptionKey:
        'आरक्षण आईडी के विरुद्ध डिलीवरी पर प्राप्त नकद भुगतान के माध्यम से निपटान किया गया',
      licenseKey: 'लाइसेंस',
      customerEmailKey: 'ग्राहक ईमेल',
      customerPhoneKey: 'ग्राहक संपर्क नंबर',
      preBookingChargeKey: 'पूर्व बुकिंग शुल्क',
      couponCoverChargeKey: 'कूपन कवर शुल्क',
      grandTotalKey: 'राशि का भुगतान',
      diningItemTotalAmountKey: 'आइटम कुल',
      diningItemDiscountAmountKey: 'आइटम छूट',
      diningCouponDiscountAmountKey: 'कूपन छूट',
      diningGrandTotalBillAmountKey: 'कुल बिल',
    },
    tiffinSubscriptionSummary: {
      purchasedSummaryKey: 'टिफ़िन सब्सक्रिप्शन खरीद सारांश',
      purchasedIdKey: 'खरीद आईडी',
      purchasedTimeKey: 'खरीद का समय',
      customerNameKey: 'ग्राहक का नाम',
      deliveryAddressKey: 'डिलीवरी पता',
      restaurantNameKey: 'रेस्टोरेंट का नाम',
      restaurantAddressKey: 'रेस्टोरेंट का पता',
      itemKey: 'आइटम',
      quantityKey: 'मात्रा',
      unitPriceKey: 'इकाई मूल्य',
      totalPriceKey: 'कुल मूल्य',
      itemTotalKey: 'कुल आइटम',
      foodServiceChargeKey: 'भोजन सेवा शुल्क',
      serviceChargeKey: 'सेवा शुल्क',
      packageChargeKey: 'पैकेजिंग शुल्क',
      packageChargeTaxKey: 'पैकेजिंग शुल्क कर',
      extraChargeKey: 'अतिरिक्त शुल्क',
      grandTotalKey: 'कुल योग',
      licenseKey: 'लाइसेंस संख्या',
      packageNameKey: 'पैकेज का नाम',
      totalOrderKey: 'कुल ऑर्डर',
      breakfast: 'नाश्ता',
      lunch: 'दोपहर का खाना',
      dinner: 'रात का खाना',
    },
    tiffinSubscriptionInvoice: {
      purchaseInvoiceKey: 'टिफिन सब्सक्रिप्शन खरीद चालान',
      taxInvoiceKey: 'कर चालान',
      digitalCopyKey: 'प्राप्तकर्ता के लिए डिजिटल प्रति',
      taxBehalfKey: 'की ओर से कर चालान -',
      legalNameKey: 'कानूनी इकाई का नाम',
      restaurantNameKey: 'रेस्तरां का नाम',
      restaurantAddressKey: 'रेस्तरां का पता',
      restaurantLicenseKey: 'रेस्तरां लाइसेंस',
      invoiceNumberKey: 'चालान संख्या',
      invoiceDateKey: 'चालान तिथि',
      customerNameKey: 'ग्राहक का नाम',
      deliveryAddressKey: 'वितरण का पता',
      serviceDescriptionKey: 'सेवा विवरण',
      serviceDescriptionValue: 'रेस्तरां सेवा',
      itemKey: 'वस्तुएं',
      grossValueKey: 'सकल मूल्य',
      discountKey: 'छूट',
      netValueKey: 'शुद्ध मूल्य',
      taxNameKey: 'कर का नाम',
      taxValueKey: 'कर का मूल्य',
      totalKey: 'कुल',
      itemTotalKey: 'वस्तुओं का कुल',
      foodServiceChargeKey: 'खाद्य सेवा शुल्क',
      serviceChargeKey: 'सेवा शुल्क',
      restaurantPackagingChargeKey: 'रेस्तरां पैकेजिंग शुल्क',
      extraChargeKey: 'अतिरिक्त शुल्क',
      totalValueKey: 'कुल मूल्य',
      amountKey: 'राशि',
      onlinePayDescriptionKey:
        'खरीद आईडी के विरुद्ध डिलीवरी पर प्राप्त डिजिटल भुगतान के माध्यम से निपटान किया गया',
      offlinePayDescriptionKey:
        'खरीद आईडी के विरुद्ध डिलीवरी पर प्राप्त नकद भुगतान के माध्यम से निपटान किया गया',
      licenseKey: 'लाइसेंस',
      packageNameKey: 'पैकेज का नाम',
      totalOrderKey: 'कुल आदेश',
      breakfast: 'नाश्ता',
      lunch: 'दोपहर का भोजन',
      dinner: 'रात्रि का भोजन',
    },
  },
  ar: {
    direction: 'rtl',
    orderSummary: {
      orderSummaryKey: 'ملخص الطلب',
      orderIdKey: 'معرف الطلب',
      orderTimeKey: 'وقت الطلب',
      customerNameKey: 'اسم العميل',
      deliveryAddressKey: 'عنوان التسليم',
      restaurantNameKey: 'اسم المطعم',
      restaurantAddressKey: 'عنوان المطعم',
      driverNameKey: 'اسم شريك التسليم',
      itemKey: 'العنصر',
      quantityKey: 'كمية',
      amountKey: 'الكمية',
      unitPriceKey: 'سعر الوحدة',
      totalPriceKey: 'السعر الإجمالي',
      itemTotalKey: 'إجمالي العنصر',
      foodServiceChargeKey: 'رسوم خدمة الطعام',
      serviceChargeKey: 'رسوم الخدمة',
      deliveryChargeKey: 'رسوم التسليم',
      deliveryTipKey: 'إكرامية التسليم',
      packageChargeKey: 'رسوم التغليف',
      packageChargeTaxKey: 'ضريبة رسوم التغليف',
      extraChargeKey: 'رسوم إضافية',
      discountChargeKey: 'خصم المبلغ',
      walletChargeKey: 'مبلغ المحفظة',
      grandTotalKey: 'المجموع الكلي',
      licenseKey: 'رقم الترخيص',
      selfPickupKey: 'الاستلام الذاتي',
    },
    orderInvoice: {
      orderInvoiceKey: 'فاتورة الطلب',
      taxInvoiceKey: 'فاتورة ضريبية',
      digitalCopyKey: 'نسخة رقمية للمستلم',
      taxBehalfKey: 'فاتورة ضريبية نيابة عن -',
      legalNameKey: 'اسم الكيان القانوني',
      restaurantNameKey: 'اسم المطعم',
      restaurantAddressKey: 'عنوان المطعم',
      restaurantLicenseKey: 'رخصة المطعم',
      invoiceNumberKey: 'رقم الفاتورة',
      invoiceDateKey: 'تاريخ الفاتورة',
      customerNameKey: 'اسم العميل',
      deliveryAddressKey: 'عنوان التسليم',
      serviceDescriptionKey: 'وصف الخدمة',
      serviceDescriptionValue: 'خدمة المطعم',
      itemKey: 'العناصر',
      grossValueKey: 'القيمة الإجمالية',
      discountKey: 'خصم',
      netValueKey: 'صافي القيمة',
      taxNameKey: 'اسم الضريبة',
      taxValueKey: 'قيمة الضريبة',
      totalKey: 'المجموع',
      itemTotalKey: 'إجمالي العناصر',
      foodServiceChargeKey: 'رسوم خدمة الطعام',
      serviceChargeKey: 'رسوم الخدمة',
      deliveryChargeKey: 'رسوم التوصيل',
      deliveryTipKey: 'إكرامية التوصيل',
      restaurantPackagingChargeKey: 'رسوم تغليف المطعم',
      extraChargeKey: 'رسوم إضافية',
      couponDiscountKey: 'خصم القسيمة',
      walletDiscountKey: 'خصم المحفظة',
      totalValueKey: 'القيمة الإجمالية',
      amountKey: 'المبلغ',
      onlinePayDescriptionKey:
        'تم السداد من خلال الدفع الرقمي المستلم عند التسليم مقابل معرف الطلب',
      offlinePayDescriptionKey:
        'تم التسوية من خلال الدفع النقدي الذي تم استلامه عند التسليم مقابل معرف الطلب',
      licenseKey: 'Lic.',
    },
    bookingSummary: {
      bookingSummaryKey: 'ملخص حجز الطعام',
      bookingIdKey: 'معرّف الحجز',
      bookingDateTimeKey: 'الجدول الزمني',
      guestCountKey: 'عدد الضيوف',
      customerNameKey: 'اسم العميل',
      customerEmailKey: 'البريد الإلكتروني',
      customerPhoneKey: 'رقم الهاتف',
      restaurantNameKey: 'اسم المطعم',
      restaurantAddressKey: 'عنوان المطعم',
      licenseKey: 'رقم الترخيص',
    },
    bookingInvoice: {
      bookingInvoiceKey: 'فاتورة حجز الطعام',
      taxInvoiceKey: 'فاتورة ضريبية',
      digitalCopyKey: 'نسخة رقمية للمستلم',
      taxBehalfKey: 'فاتورة ضريبية نيابة عن -',
      legalNameKey: 'الاسم القانوني للكيان',
      restaurantNameKey: 'اسم المطعم',
      restaurantAddressKey: 'عنوان المطعم',
      restaurantLicenseKey: 'رخصة المطعم',
      invoiceNumberKey: 'رقم الفاتورة',
      invoiceDateKey: 'تاريخ الفاتورة',
      customerNameKey: 'اسم العميل',
      serviceDescriptionKey: 'وصف الخدمة',
      serviceDescriptionValue: 'خدمة المطعم',
      onlinePayDescriptionKey:
        'تم التسوية من خلال الدفع الرقمي المستلم عند التسليم مقابل معرف الحجز',
      offlinePayDescriptionKey:
        'تم التسوية من خلال الدفع النقدي المستلم عند التسليم مقابل معرف الحجز',
      licenseKey: 'ترخيص',
      customerEmailKey: 'البريد الإلكتروني للعميل',
      customerPhoneKey: 'رقم اتصال العميل',
      preBookingChargeKey: 'رسوم الحجز المسبق',
      couponCoverChargeKey: 'رسوم تغطية القسيمة',
      grandTotalKey: 'المبلغ المدفوع',
      diningItemTotalAmountKey: 'إجمالي العناصر',
      diningItemDiscountAmountKey: 'خصم العناصر',
      diningCouponDiscountAmountKey: 'خصم القسيمة',
      diningGrandTotalBillAmountKey: 'إجمالي الفاتورة',
    },
    tiffinSubscriptionSummary: {
      purchasedSummaryKey: 'ملخص شراء اشتراك التيفين',
      purchasedIdKey: 'معرّف الشراء',
      purchasedTimeKey: 'وقت الشراء',
      customerNameKey: 'اسم العميل',
      deliveryAddressKey: 'عنوان التوصيل',
      restaurantNameKey: 'اسم المطعم',
      restaurantAddressKey: 'عنوان المطعم',
      itemKey: 'العنصر',
      quantityKey: 'الكمية',
      unitPriceKey: 'سعر الوحدة',
      totalPriceKey: 'السعر الإجمالي',
      itemTotalKey: 'إجمالي العناصر',
      foodServiceChargeKey: 'رسوم خدمة الطعام',
      serviceChargeKey: 'رسوم الخدمة',
      packageChargeKey: 'رسوم التغليف',
      packageChargeTaxKey: 'ضريبة رسوم التغليف',
      extraChargeKey: 'رسوم إضافية',
      grandTotalKey: 'الإجمالي الكلي',
      licenseKey: 'رقم الترخيص',
      packageNameKey: 'اسم الباقة',
      totalOrderKey: 'إجمالي الطلبات',
      breakfast: 'الفطور',
      lunch: 'الغداء',
      dinner: 'العشاء',
    },
    tiffinSubscriptionInvoice: {
      purchaseInvoiceKey: 'فاتورة شراء اشتراك التيفين',
      taxInvoiceKey: 'فاتورة ضريبية',
      digitalCopyKey: 'نسخة رقمية للمستلم',
      taxBehalfKey: 'فاتورة ضريبية نيابةً عن -',
      legalNameKey: 'الاسم القانوني للكيان',
      restaurantNameKey: 'اسم المطعم',
      restaurantAddressKey: 'عنوان المطعم',
      restaurantLicenseKey: 'رخصة المطعم',
      invoiceNumberKey: 'رقم الفاتورة',
      invoiceDateKey: 'تاريخ الفاتورة',
      customerNameKey: 'اسم العميل',
      deliveryAddressKey: 'عنوان التوصيل',
      serviceDescriptionKey: 'وصف الخدمة',
      serviceDescriptionValue: 'خدمة المطعم',
      itemKey: 'العناصر',
      grossValueKey: 'القيمة الإجمالية',
      discountKey: 'الخصم',
      netValueKey: 'القيمة الصافية',
      taxNameKey: 'اسم الضريبة',
      taxValueKey: 'قيمة الضريبة',
      totalKey: 'الإجمالي',
      itemTotalKey: 'إجمالي العناصر',
      foodServiceChargeKey: 'رسوم خدمة الطعام',
      serviceChargeKey: 'رسوم الخدمة',
      restaurantPackagingChargeKey: 'رسوم تغليف المطعم',
      extraChargeKey: 'رسوم إضافية',
      totalValueKey: 'القيمة الإجمالية',
      amountKey: 'المبلغ',
      onlinePayDescriptionKey:
        'تمت التسوية من خلال الدفع الرقمي المستلم عند التسليم مقابل رقم الشراء',
      offlinePayDescriptionKey:
        'تمت التسوية من خلال الدفع النقدي المستلم عند التسليم مقابل رقم الشراء',
      licenseKey: 'رخصة',
      packageNameKey: 'اسم الباقة',
      totalOrderKey: 'إجمالي الطلبات',
      breakfast: 'إفطار',
      lunch: 'غداء',
      dinner: 'عشاء',
    },
  },
  es: {
    direction: 'ltr',
    orderSummary: {
      orderSummaryKey: 'Resumen del pedido',
      orderIdKey: 'Identificación del pedido',
      orderTimeKey: 'Hora de realizar el pedido',
      customerNameKey: 'Nombre del cliente',
      deliveryAddressKey: 'Dirección de entrega',
      restaurantNameKey: 'Nombre del restaurante',
      restaurantAddressKey: 'Dirección del restaurante',
      driverNameKey: 'Nombre del socio de entrega',
      itemKey: 'Artículo',
      quantityKey: 'Cantidad',
      unitPriceKey: 'Precio unitario',
      totalPriceKey: 'Precio total',
      itemTotalKey: 'Total del artículo',
      foodServiceChargeKey: 'Cargo por servicio de comida',
      serviceChargeKey: 'Cargo por servicio',
      deliveryChargeKey: 'Cargo por entrega',
      deliveryTipKey: 'Propina por entrega',
      packageChargeKey: 'Cargo por embalaje',
      packageChargeTaxKey: 'Impuesto por cargo por embalaje',
      extraChargeKey: 'Cargo adicional',
      discountChargeKey: 'Monto del descuento',
      walletChargeKey: 'Monto de la billetera',
      grandTotalKey: 'Total general',
      licenseKey: 'Número de licencia',
      selfPickupKey: 'Recogida por cuenta propia',
    },
    orderInvoice: {
      orderInvoiceKey: 'Factura de pedido',
      taxInvoiceKey: 'Factura fiscal',
      digitalCopyKey: 'Copia digital para destinatario',
      taxBehalfKey: 'Factura fiscal en nombre de -',
      legalNameKey: 'Nombre de entidad legal',
      restaurantNameKey: 'Nombre del restaurante',
      restaurantAddressKey: 'Dirección del restaurante',
      restaurantLicenseKey: 'Licencia del restaurante',
      invoiceNumberKey: 'N.º de factura',
      invoiceDateKey: 'Fecha de factura',
      customerNameKey: 'Nombre del cliente',
      deliveryAddressKey: 'Dirección de entrega',
      serviceDescriptionKey: 'Descripción del servicio',
      serviceDescriptionValue: 'Servicio de restaurante',
      itemKey: 'Artículos',
      grossValueKey: 'Valor bruto',
      discountKey: 'Descuento',
      netValueKey: 'Valor neto',
      taxNameKey: 'Nombre del impuesto',
      taxValueKey: 'Valor del impuesto',
      totalKey: 'Total',
      itemTotalKey: 'Total de artículo(s)',
      foodServiceChargeKey: 'Cargo por servicio de comida',
      serviceChargeKey: 'Cargo por servicio',
      deliveryChargeKey: 'Cargo por entrega',
      deliveryTipKey: 'Propina por entrega',
      restaurantPackagingChargeKey: 'Cargo por embalaje del restaurante',
      extraChargeKey: 'Cargo adicional',
      couponDiscountKey: 'Cupón de descuento',
      walletDiscountKey: 'Descuento de billetera',
      totalValueKey: 'Valor total',
      amountKey: 'Monto',
      onlinePayDescriptionKey:
        'liquidado a través del pago digital recibido en el momento de la entrega contra el ID del pedido',
      offlinePayDescriptionKey:
        'liquidado a través del pago en efectivo recibido en el momento de la entrega contra el ID del pedido',
      licenseKey: 'Lic.',
    },
    bookingSummary: {
      bookingSummaryKey: 'Resumen de reserva de comedor',
      bookingIdKey: 'ID de reserva',
      bookingDateTimeKey: 'Programado',
      guestCountKey: 'Número de invitados',
      customerNameKey: 'Nombre del cliente',
      customerEmailKey: 'Correo electrónico',
      customerPhoneKey: 'Teléfono',
      restaurantNameKey: 'Nombre del restaurante',
      restaurantAddressKey: 'Dirección del restaurante',
      licenseKey: 'N.º de licencia',
    },
    bookingInvoice: {
      bookingInvoiceKey: 'Factura de reserva de comedor',
      taxInvoiceKey: 'Factura fiscal',
      digitalCopyKey: 'Copia digital para el destinatario',
      taxBehalfKey: 'Factura fiscal en nombre de -',
      legalNameKey: 'Nombre legal de la entidad',
      restaurantNameKey: 'Nombre del restaurante',
      restaurantAddressKey: 'Dirección del restaurante',
      restaurantLicenseKey: 'Licencia del restaurante',
      invoiceNumberKey: 'N.º de factura',
      invoiceDateKey: 'Fecha de la factura',
      customerNameKey: 'Nombre del cliente',
      serviceDescriptionKey: 'Descripción del servicio',
      serviceDescriptionValue: 'Servicio del restaurante',
      onlinePayDescriptionKey:
        'liquidado mediante pago digital recibido en la entrega contra el ID de reserva',
      offlinePayDescriptionKey:
        'liquidado mediante pago en efectivo recibido en la entrega contra el ID de reserva',
      licenseKey: 'Lic.',
      customerEmailKey: 'Correo electrónico del cliente',
      customerPhoneKey: 'N.º de contacto del cliente',
      preBookingChargeKey: 'Cargo por reserva previa',
      couponCoverChargeKey: 'Cargo por cobertura de cupón',
      grandTotalKey: 'Cantidad pagada',
      diningItemTotalAmountKey: 'Total de artículos',
      diningItemDiscountAmountKey: 'Descuento de artículos',
      diningCouponDiscountAmountKey: 'Descuento de cupón',
      diningGrandTotalBillAmountKey: 'Total de la factura',
    },
    tiffinSubscriptionSummary: {
      purchasedSummaryKey: 'Resumen de compra de suscripción de tiffin',
      purchasedIdKey: 'ID de compra',
      purchasedTimeKey: 'Hora de compra',
      customerNameKey: 'Nombre del cliente',
      deliveryAddressKey: 'Dirección de entrega',
      restaurantNameKey: 'Nombre del restaurante',
      restaurantAddressKey: 'Dirección del restaurante',
      itemKey: 'Artículo',
      quantityKey: 'Cantidad',
      unitPriceKey: 'Precio unitario',
      totalPriceKey: 'Precio total',
      itemTotalKey: 'Total de artículos',
      foodServiceChargeKey: 'Cargo por servicio de comida',
      serviceChargeKey: 'Cargo por servicio',
      packageChargeKey: 'Cargo por embalaje',
      packageChargeTaxKey: 'Impuesto del cargo por embalaje',
      extraChargeKey: 'Cargo extra',
      grandTotalKey: 'Total general',
      licenseKey: 'Lic. No.',
      packageNameKey: 'Nombre del paquete',
      totalOrderKey: 'Pedidos totales',
      breakfast: 'Desayuno',
      lunch: 'Almuerzo',
      dinner: 'Cena',
    },
    tiffinSubscriptionInvoice: {
      purchaseInvoiceKey: 'Factura de Compra de Suscripción de Tiffin',
      taxInvoiceKey: 'Factura de Impuestos',
      digitalCopyKey: 'Copia Digital para el Destinatario',
      taxBehalfKey: 'Factura de Impuestos en nombre de -',
      legalNameKey: 'Nombre Legal de la Entidad',
      restaurantNameKey: 'Nombre del Restaurante',
      restaurantAddressKey: 'Dirección del Restaurante',
      restaurantLicenseKey: 'Licencia del Restaurante',
      invoiceNumberKey: 'N.º de Factura',
      invoiceDateKey: 'Fecha de Factura',
      customerNameKey: 'Nombre del Cliente',
      deliveryAddressKey: 'Dirección de Entrega',
      serviceDescriptionKey: 'Descripción del Servicio',
      serviceDescriptionValue: 'Servicio del Restaurante',
      itemKey: 'Artículos',
      grossValueKey: 'Valor Bruto',
      discountKey: 'Descuento',
      netValueKey: 'Valor Neto',
      taxNameKey: 'Nombre del Impuesto',
      taxValueKey: 'Valor del Impuesto',
      totalKey: 'Total',
      itemTotalKey: 'Total de Artículos',
      foodServiceChargeKey: 'Cargo por Servicio de Comida',
      serviceChargeKey: 'Cargo por Servicio',
      restaurantPackagingChargeKey: 'Cargo por Empaque del Restaurante',
      extraChargeKey: 'Cargo Extra',
      totalValueKey: 'Valor Total',
      amountKey: 'Monto',
      onlinePayDescriptionKey:
        'liquidado mediante pago digital recibido en la entrega contra el ID de compra',
      offlinePayDescriptionKey:
        'liquidado mediante pago en efectivo recibido en la entrega contra el ID de compra',
      licenseKey: 'Lic.',
      packageNameKey: 'Nombre del Paquete',
      totalOrderKey: 'Pedidos Totales',
      breakfast: 'Desayuno',
      lunch: 'Almuerzo',
      dinner: 'Cena',
    },
  },
};

module.exports = apiLocaleTranslations;

