/**
 * LocalWala – Local Commerce & Delivery Platform
 * (NodeJS, MongoDB, Angular & Flutter)
 *
 * Copyright © 2026 WeWorkLocal Private Limited
 * https://weworklocal.in/
 *
 * WeWorkLocal Private Limited
 * This source code is confidential.
 *
 * Ownership Fingerprint:
 * LWL|WWL|2026|LOCALWALA|NODE
 *
 * Phase 3.1 - the restaurant domain's public entry point.
 * Restaurants, menus, catalogue wiring, facilities, staff relationships.
 *
 * GENERATED by tools/domain-inventory.js --write-domains. Do not edit by
 * hand: `npm run domain:check` fails if this file drifts from the
 * classification in the inventory tool.
 *
 * Re-exports the same names the src/services and src/models barrels
 * export today, so moving a consumer to this file is a one-line change.
 */

import * as addonsService from '../../services/addons.service';
import * as bannersService from '../../services/banners.service';
import * as categoryService from '../../services/category.service';
import * as cuisineService from '../../services/cuisine.service';
import * as foodCampaignRequestService from '../../services/food.campaign.request.service';
import * as foodCampaignService from '../../services/food.campaign.service';
import * as foodOrderReviewService from '../../services/food.order.review.service';
import * as foodService from '../../services/food.service';
import * as foodTaxationService from '../../services/food.taxation.service';
import * as hideRestaurantReasonService from '../../services/hide.restaurant.reason.service';
import * as hideRestaurantService from '../../services/hide.restaurant.service';
import * as joiningFormService from '../../services/joining.form.service';
import * as kitchenOwnerService from '../../services/kitchen.owner.service';
import * as kitchenOwnerSettingService from '../../services/kitchen.owner.setting.service';
import * as restaurantCampaignRequestService from '../../services/restaurant.campaign.request.service';
import * as restaurantCampaignService from '../../services/restaurant.campaign.service';
import * as restaurantComplaintsService from '../../services/restaurant.complaints.service';
import * as restaurantExpenseService from '../../services/restaurant.expense.service';
import * as restaurantExtraDetailsService from '../../services/restaurant.extra.details.service';
import * as restaurantFacilitiesService from '../../services/restaurant.facilities.service';
import * as restaurantFoodLicenseService from '../../services/restaurant.food.license.service';
import * as restaurantJoiningRequestService from '../../services/restaurant.joining.request.service';
import * as restaurantNoticeService from '../../services/restaurant.notice.service';
import * as restaurantOrderReviewService from '../../services/restaurant.order.review.service';
import * as restaurantPayoutMethodService from '../../services/restaurant.payout.method.service';
import * as restaurantPosTableOrderCommissionService from '../../services/restaurant.pos.table.order.commission.service';
import * as restaurantService from '../../services/restaurant.service';
import * as restaurantSettingsService from '../../services/restaurant.settings.service';
import * as restaurantTableService from '../../services/restaurant.table.service';
import * as restaurantTypeService from '../../services/restaurant.type.service';
import * as subCategoryService from '../../services/sub.category.service';
import * as vendorCategoryService from '../../services/vendor.category.service';
import * as vendorSubCategoryService from '../../services/vendor.sub.category.service';
import Addons from '../../models/addons.model';
import Banner from '../../models/banners.model';
import Category from '../../models/category.model';
import Coupon from '../../models/coupons.model';
import Cuisine from '../../models/cuisine.model';
import DiningCoupon from '../../models/dining.coupons.model';
import FoodCampaign from '../../models/food.campaign.model';
import FoodCampaignRequest from '../../models/food.campaign.request.model';
import Food from '../../models/food.model';
import FoodOrderReview from '../../models/food.order.review';
import FoodTaxation from '../../models/food.taxation.model';
import HideRestaurant from '../../models/hide.restaurant.model';
import HideRestaurantReason from '../../models/hide.restaurant.reason.model';
import JoiningForm from '../../models/joining.form.model';
import KitchenOrder from '../../models/kitchen.order.model';
import KitchenOwner from '../../models/kitchen.owner.model';
import KitchenOwnerSetting from '../../models/kitchen.owner.setting.model';
import RestaurantCampaign from '../../models/restaurant.campaign.model';
import RestaurantCampaignRequest from '../../models/restaurant.campaign.request.model';
import RestaurantComplaints from '../../models/restaurant.complaints.model';
import RestaurantExpense from '../../models/restaurant.expense.model';
import RestaurantExtraDetail from '../../models/restaurant.extra.details.model';
import RestaurantFacility from '../../models/restaurant.facilities.model';
import RestaurantFoodLicense from '../../models/restaurant.food.license.model';
import RestaurantJoiningRequest from '../../models/restaurant.joining.request.model';
import Restaurant from '../../models/restaurant.model';
import RestaurantNotice from '../../models/restaurant.notice.model';
import RestaurantOrderReview from '../../models/restaurant.order.reviews.model';
import RestaurantPayoutMethod from '../../models/restaurant.payout.method.model';
import RestaurantPosTableOrderCommission from '../../models/restaurant.pos.table.order.commission.model';
import RestaurantSettings from '../../models/restaurant.settings.model';
import RestaurantTable from '../../models/restaurant.table.model';
import RestaurantType from '../../models/restaurant.type.model';
import SubCategory from '../../models/sub.category.model';
import VendorCategory from '../../models/vendor.category.model';
import VendorSubCategory from '../../models/vendor.sub.category.model';

export { addonsService };
export { bannersService };
export { categoryService };
export { cuisineService };
export { foodCampaignRequestService };
export { foodCampaignService };
export { foodOrderReviewService };
export { foodService };
export { foodTaxationService };
export { hideRestaurantReasonService };
export { hideRestaurantService };
export { joiningFormService };
export { kitchenOwnerService };
export { kitchenOwnerSettingService };
export { restaurantCampaignRequestService };
export { restaurantCampaignService };
export { restaurantComplaintsService };
export { restaurantExpenseService };
export { restaurantExtraDetailsService };
export { restaurantFacilitiesService };
export { restaurantFoodLicenseService };
export { restaurantJoiningRequestService };
export { restaurantNoticeService };
export { restaurantOrderReviewService };
export { restaurantPayoutMethodService };
export { restaurantPosTableOrderCommissionService };
export { restaurantService };
export { restaurantSettingsService };
export { restaurantTableService };
export { restaurantTypeService };
export { subCategoryService };
export { vendorCategoryService };
export { vendorSubCategoryService };
export { Addons };
export { Banner };
export { Category };
export { Coupon };
export { Cuisine };
export { DiningCoupon };
export { FoodCampaign };
export { FoodCampaignRequest };
export { Food };
export { FoodOrderReview };
export { FoodTaxation };
export { HideRestaurant };
export { HideRestaurantReason };
export { JoiningForm };
export { KitchenOrder };
export { KitchenOwner };
export { KitchenOwnerSetting };
export { RestaurantCampaign };
export { RestaurantCampaignRequest };
export { RestaurantComplaints };
export { RestaurantExpense };
export { RestaurantExtraDetail };
export { RestaurantFacility };
export { RestaurantFoodLicense };
export { RestaurantJoiningRequest };
export { Restaurant };
export { RestaurantNotice };
export { RestaurantOrderReview };
export { RestaurantPayoutMethod };
export { RestaurantPosTableOrderCommission };
export { RestaurantSettings };
export { RestaurantTable };
export { RestaurantType };
export { SubCategory };
export { VendorCategory };
export { VendorSubCategory };
