/**
 * LocalWala – Local Commerce & Delivery Platform
 * (NodeJS, MongoDB, Angular & Flutter)
 *
 * Copyright © 2026 WeWorkLocal Private Limited
 * https://weworklocal.in/
 *
 * WeWorkLocal Private Limited
 * This source code is confidential.
 *
 * Ownership Fingerprint:
 * LWL|WWL|2026|LOCALWALA|NODE
 *
 * Phase 3.1 - the storage domain's public entry point.
 * Media and file storage (local, GCS, Azure, S3).
 *
 * GENERATED by tools/domain-inventory.js --write-domains. Do not edit by
 * hand: `npm run domain:check` fails if this file drifts from the
 * classification in the inventory tool.
 *
 * Re-exports the same names the src/services and src/models barrels
 * export today, so moving a consumer to this file is a one-line change.
 */

import * as mediaService from '../../services/media.service';
import * as mediaStorageSettingService from '../../services/media.storage.setting.service';
import Media from '../../models/media.model';
import MediaStorageSetting from '../../models/media.storage.setting.model';

export { mediaService };
export { mediaStorageSettingService };
export { Media };
export { MediaStorageSetting };
