/**
 * Phase 3.3: split services/orders.service.js without changing behaviour.
 *
 * The split is a cut-and-paste, so the tool's whole job is to make that
 * literal: it copies function text *verbatim*, works out from the moved text
 * which of the original file's imports those functions actually need, and
 * rewrites the original to import them from the new module. Nothing is
 * reformatted, renamed or "improved" - if this tool ever needs to understand
 * a function body, it is doing too much.
 *
 * Two things it will not let slide:
 *   - a require left behind that nothing uses any more, because an unused
 *     import is a new lint warning and this repo treats that as a regression;
 *   - a moved function with no caller left, which would make the split a dead
 *     extraction rather than a boundary.
 *
 * Why the first slice is the analytics cluster: those eight helpers are not
 * part of orders.service's public surface, so moving them cannot change what
 * any consumer sees, and they form one clean cluster (measured: 99 local
 * functions, no module-level mutable state, 1 of 86 exported functions calling
 * another).
 *
 * Usage:
 *   node tools/split-orders.js --plan
 *   node tools/split-orders.js --apply
 *   node tools/split-orders.js --verify     (byte-identity against git HEAD)
 */
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const API_ROOT = path.resolve(__dirname, '..');
const SRC_FILE = path.join(API_ROOT, 'src', 'services', 'orders.service.js');

/** The analytics cluster: the eight earning-breakdown queries. */
const MOVED = [
  'orderEarningBreakdown',
  'posOrderEarningBreakdown',
  'tableOrderEarningBreakdown',
  'diningBookingEarningBreakdown',
  'cityBasedOrderEarningBreakdown',
  'cityBasedPOSOrderEarningBreakdown',
  'cityBasedTableOrderEarningBreakdown',
  'cityBasedDiningBookingEarningBreakdown',
];

const OUT_MODULE = './orders.analytics.internal';
const OUT_FILE = path.join(path.dirname(SRC_FILE), 'orders.analytics.internal.js');

const HEADER = [
  '/**',
  ' * LocalWala - Local Commerce & Delivery Platform',
  ' * (NodeJS, MongoDB, Angular & Flutter)',
  ' *',
  ' * Copyright (c) 2026 WeWorkLocal Private Limited',
  ' * https://weworklocal.in/',
  ' *',
  ' * WeWorkLocal Private Limited',
  ' * This source code is confidential.',
  ' *',
  ' * Ownership Fingerprint:',
  ' * LWL|WWL|2026|LOCALWALA|NODE',
  ' *',
  ' * Phase 3.3: the order analytics kernel, split out of orders.service.js.',
  ' *',
  ' * The eight earning-breakdown queries behind adminDashboard,',
  ' * accountantDashboard and cityzenDashboard. Not part of the service public',
  ' * surface, so moving them cannot change what any consumer sees.',
  ' * GENERATED by tools/split-orders.js - do not hand-edit.',
  ' */',
  '',
].join('\n');

const readSource = () => fs.readFileSync(SRC_FILE, 'utf8');
const uses = (text, name) => new RegExp(`\\b${name.replace(/\$/g, '\\$')}\\b`).test(text);

/** Is `name` among the bindings the original pulls in from the new module? */
function importsFromNewModule(src, name) {
  return requireBlocks(src)
    .filter((b) => b.text.includes(OUT_MODULE))
    .some((b) => b.names.includes(name));
}

/**
 * Every top-level require, with the source line range it occupies. Blocks span
 * lines (destructured imports are usually wrapped), so they have to be cut as
 * ranges rather than as single lines.
 */
function requireBlocks(src) {
  const lines = src.split('\n');
  const blocks = [];
  for (let i = 0; i < lines.length; i++) {
    if (!/^const\s.*=\s*require\(/.test(lines[i]) && !/^const\s*\{\s*$/.test(lines[i])) continue;
    let end = i;
    let stmt = lines[i];
    while (end < lines.length && !/;\s*$/.test(stmt)) {
      end++;
      stmt += `\n${lines[end]}`;
    }
    const names = [];
    const braced = stmt.match(/\{([\s\S]*?)\}/);
    if (braced) {
      for (const part of braced[1].split(',')) {
        const n = part.split(':').pop().trim();
        if (n) names.push(n);
      }
    } else {
      const m = stmt.match(/^const\s+([A-Za-z_$][\w$]*)\s*=/);
      if (m) names.push(m[1]);
    }
    blocks.push({ start: i, end, names, text: stmt, statement: stmt.replace(/\n\s*/g, ' ') });
  }
  return blocks;
}

/** Cut a top-level function's text verbatim, up to the next top-level declaration. */
function sliceTopLevel(src, name) {
  const lines = src.split('\n');
  let start = -1;
  for (let i = 0; i < lines.length; i++) {
    if (
      new RegExp(`^(?:const|let|var)\\s+${name}\\s*=\\s*(?:async\\s*)?\\(`).test(lines[i]) ||
      new RegExp(`^(?:async\\s+)?function\\s+${name}\\b`).test(lines[i])
    ) {
      start = i;
      break;
    }
  }
  if (start < 0) throw new Error(`function not found at top level: ${name}`);

  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    if (
      /^(?:const|let|var)\s+[A-Za-z_$][\w$]*\s*=/.test(lines[i]) ||
      /^(?:async\s+)?function\s+[A-Za-z_$][\w$]*/.test(lines[i]) ||
      /^module\.exports/.test(lines[i])
    ) {
      end = i;
      break;
    }
  }
  while (end > start + 1 && lines[end - 1].trim() === '') end--;
  return { start, end, text: lines.slice(start, end).join('\n') };
}

function plan() {
  const src = readSource();
  const slices = MOVED.map((n) => ({ name: n, ...sliceTopLevel(src, n) })).sort(
    (a, b) => a.start - b.start
  );
  const movedText = slices.map((s) => s.text).join('\n\n');

  const lines = src.split('\n');
  const drop = new Set();
  for (const s of slices) for (let i = s.start; i < s.end; i++) drop.add(i);

  // Collapse the blank runs the removal leaves behind, keeping line numbers
  // meaningful for the require-block pass below.
  const survivors = [];
  let blanks = 0;
  for (let i = 0; i < lines.length; i++) {
    if (drop.has(i)) continue;
    if (lines[i].trim() === '') {
      blanks++;
      if (blanks <= 1) survivors.push({ i, text: lines[i] });
      continue;
    }
    blanks = 0;
    survivors.push({ i, text: lines[i] });
  }

  const survivorText = survivors.map((s) => s.text).join('\n');

  // Imports for the new module: only what the moved text references. This has
  // to be per *name*, not per require statement - '../models' is a single
  // destructured require of 31 names, and copying it wholesale would import 26
  // names the new file never touches, i.e. 26 new lint warnings.
  const blocks = requireBlocks(src);
  const neededForMoved = [];
  for (const b of blocks) {
    const keep = b.names.filter((n) => uses(movedText, n));
    if (!keep.length) continue;
    const source = b.text.match(/require\((['"])([^'"]+)\1\)/);
    if (!source) continue;
    if (keep.length === 1 && !b.text.includes('{')) {
      neededForMoved.push(`const ${keep[0]} = require('${source[2]}');`);
    } else {
      // Keep the repo's own wrapped, one-name-per-line destructuring style.
      const body = keep.map((n) => `  ${n},`).join('\n');
      neededForMoved.push(`const {\n${body}\n} = require('${source[2]}');`);
    }
  }

  // Requires in the original that the moved text was the last user of.
  const orphaned = blocks.filter(
    (b) => !b.names.some((n) => uses(survivorText, n)) && b.names.some((n) => uses(movedText, n))
  );

  const stillCalled = MOVED.filter((n) => new RegExp(`\\b${n}\\s*\\(`).test(survivorText));
  const survivorsDecls = survivors
    .map((s) => {
      const m = s.text.match(/^(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s*)?\(/);
      return m ? { name: m[1], i: survivors.indexOf(s) } : null;
    })
    .filter(Boolean);
  const callSites = {};
  for (const name of stillCalled) {
    const re = new RegExp(`\\b${name}\\s*\\(`);
    const owners = [];
    survivorsDecls.forEach((d, idx) => {
      const from = d.i;
      const to = idx + 1 < survivorsDecls.length ? survivorsDecls[idx + 1].i : survivors.length;
      if (survivors.slice(from, to).some((s) => re.test(s.text))) owners.push(d.name);
    });
    callSites[name] = owners;
  }

  // The source's exact trailing byte run, re-appended verbatim. This file ends
  // `};\n\r\n` - the stray `\r` line is pre-existing - and rebuilding the tail
  // from the collapsed survivors produced `};\n\r`, which `git diff --check`
  // reports as trailing whitespace on a line the split never meant to touch.
  const tail = /(\n[\r\n]*)$/.exec(src)?.[0] || '\n';

  return { src, slices, movedText, neededForMoved, orphaned, stillCalled, callSites, survivors, tail };
}

function renderNewFile(p) {
  return `${HEADER}\n${p.neededForMoved.join('\n')}\n\n${p.movedText}\n\nmodule.exports = {\n${MOVED.map((n) => `  ${n},`).join('\n')}\n};\n`;
}

function renderOriginal(p) {
  const indexOf = new Map(p.survivors.map((s, idx) => [s.i, idx]));

  // Pass 1: drop require blocks that nothing uses any more.
  const dropSet = new Set();
  for (const b of p.orphaned) {
    for (let i = b.start; i <= b.end; i++) if (indexOf.has(i)) dropSet.add(indexOf.get(i));
  }
  const keptObjs = p.survivors.filter((_, idx) => !dropSet.has(idx));

  // Pass 2: prune individual names out of the requires that are still needed.
  // '../models' is one destructured require of 31 names; if the moved
  // functions were the last users of one of them, the block survives but must
  // shrink, or that name becomes a new unused-import warning.
  //
  // This walks *blocks*, not runs of require-looking lines. The import block of
  // this file is 14 separate requires on 14 consecutive lines with no blanks
  // between them, so treating a contiguous run as one unit silently merges all
  // 14 into one - and re-emitting that merged unit verbatim would prune
  // nothing, while pruning it would delete the other 13 imports.
  const blocks = requireBlocks(p.src).map((b) => {
    const idxs = [];
    for (let i = b.start; i <= b.end; i++) if (indexOf.has(i)) idxs.push(indexOf.get(i));
    return { b, idxs: idxs.filter((x) => !dropSet.has(x)) };
  });
  const requireIdx = new Set(blocks.flatMap((x) => x.idxs));
  const firstIdx = new Map(blocks.filter((x) => x.idxs.length).map((x) => [x.idxs[0], x]));

  // Usage is tested against the body only: a require line always mentions the
  // names it imports, so including them would mark every name as used.
  const bodyText = keptObjs
    .filter((_, idx) => !requireIdx.has(idx))
    .map((s) => s.text)
    .join('\n');

  const out = [];
  let i = 0;
  while (i < keptObjs.length) {
    const entry = firstIdx.get(i);
    if (!entry) {
      out.push(keptObjs[i].text);
      i++;
      continue;
    }
    const { b, idxs } = entry;
    const keep = b.names.filter((n) => uses(bodyText, n));
    const source = b.text.match(/require\((['"])([^'"]+)\1\)/);
    const multiline = b.text.includes('\n');

    if (!keep.length || !source || keep.length === b.names.length) {
      // Unchanged, or nothing left to import: emit verbatim.
      out.push(...idxs.map((x) => keptObjs[x].text));
    } else if (!multiline && !b.text.includes('{')) {
      out.push(`const ${keep[0]} = require('${source[2]}');`);
    } else if (multiline) {
      out.push(`const {\n${keep.map((n) => `  ${n},`).join('\n')}\n} = require('${source[2]}');`);
    } else {
      out.push(`const { ${keep.join(', ')} } = require('${source[2]}');`);
    }
    i = idxs[idxs.length - 1] + 1;
  }

  let insertAt = 0;
  out.forEach((l, idx) => {
    if (/^const\s.*=\s*require\(/.test(l)) insertAt = idx + 1;
  });
  out.splice(
    insertAt,
    0,
    `const { ${MOVED.join(', ')} } = require('${OUT_MODULE}');`
  );

  // Hand the trailing bytes back to the source rather than re-deriving them.
  while (out.length && out[out.length - 1].trim() === '') out.pop();
  return `${out.join('\n')}${p.tail}`;
}

function main() {
  const args = process.argv.slice(2);

  if (args.includes('--verify')) {
    // Verify reads the original from git HEAD rather than planning against the
    // working copy: by this point the functions are gone from
    // orders.service.js, so plan() would slice a file that no longer has them.
    const original = execFileSync('git', ['show', 'HEAD:API/src/services/orders.service.js'], {
      cwd: API_ROOT,
      encoding: 'utf8',
    });
    const newFile = fs.readFileSync(OUT_FILE, 'utf8');
    const report = [];
    let ok = true;
    for (const name of MOVED) {
      const before = sliceTopLevel(original, name).text;
      if (!newFile.includes(before)) {
        report.push(`  MISMATCH  ${name}`);
        ok = false;
      } else {
        report.push(`  identical ${name}  (${before.split('\n').length} lines)`);
      }
    }
    const nowSrc = readSource();
    for (const name of MOVED) {
      if (new RegExp(`^const ${name}\\s*=\\s*(?:async\\s*)?\\(`, 'm').test(nowSrc)) {
        report.push(`  STILL DEFINED IN THE ORIGINAL  ${name}`);
        ok = false;
      }
      if (!importsFromNewModule(nowSrc, name)) {
        report.push(`  NOT IMPORTED BY THE ORIGINAL  ${name}`);
        ok = false;
      }
    }
    process.stdout.write(`${report.join('\n')}\n${ok ? 'VERIFY OK' : 'VERIFY FAILED'}\n`);
    return ok ? 0 : 1;
  }

  const p = plan();

  if (args.includes('--plan')) {
    const out = [
      `orders.service.js    : ${p.src.split('\n').length} lines`,
      `moved text           : ${p.movedText.split('\n').length} lines, ${p.slices.length} functions`,
      `imports for the new module : ${p.neededForMoved.length}`,
      ...p.neededForMoved.map((s) => `  ${s}`),
      `requires orphaned in the original : ${p.orphaned.length}`,
      ...p.orphaned.map((b) => `  ${b.names.join(', ')}  (from line ${b.start + 1})`),
      `moved functions still called : ${p.stillCalled.length}`,
      ...Object.entries(p.callSites).map(([k, v]) => `  ${k} <- ${v.join(', ') || '(none)'}`),
      '',
    ];
    process.stdout.write(out.join('\n'));
    return 0;
  }

  if (args.includes('--apply')) {
    fs.writeFileSync(OUT_FILE, renderNewFile(p), 'utf8');
    fs.writeFileSync(SRC_FILE, renderOriginal(p), 'utf8');
    process.stdout.write(
      `wrote ${path.relative(API_ROOT, OUT_FILE)}\nupdated ${path.relative(API_ROOT, SRC_FILE)}\n`
    );
    for (const f of [OUT_FILE, SRC_FILE]) {
      try {
        execFileSync(process.execPath, ['--check', f], { stdio: 'pipe' });
      } catch (err) {
        process.stderr.write(`syntax error in ${f}:\n${err.stderr}\n`);
        return 1;
      }
    }
    process.stdout.write('both files parse\n');
    return 0;
  }

  process.stdout.write('usage: --plan | --apply | --verify\n');
  return 2;
}

process.exit(main());
