/**
 * LocalWala – Local Commerce & Delivery Platform
 * (NodeJS, MongoDB, Angular & Flutter)
 *
 * Copyright © 2026 WeWorkLocal Private Limited
 * https://weworklocal.in/
 *
 * WeWorkLocal Private Limited
 * This source code is confidential.
 *
 * Ownership Fingerprint:
 * LWL|WWL|2026|LOCALWALA|NODE
 *
 * Phase 3.1 - the dining domain's public entry point.
 * Dining-specific campaigns, notices, dining configuration.
 *
 * GENERATED by tools/domain-inventory.js --write-domains. Do not edit by
 * hand: `npm run domain:check` fails if this file drifts from the
 * classification in the inventory tool.
 *
 * Re-exports the same names the src/services and src/models barrels
 * export today, so moving a consumer to this file is a one-line change.
 */

import * as diningCampaignRequestService from '../../services/dining.campaign.request.service';
import * as diningCampaignService from '../../services/dining.campaign.service';
import * as diningCategoryService from '../../services/dining.category.service';
import * as diningNoticeService from '../../services/dining.notice.service';
import DiningCampaign from '../../models/dining.campaign.model';
import DiningCampaignRequest from '../../models/dining.campaign.request.model';
import DiningCategory from '../../models/dining.category.model';
import DiningtNotice from '../../models/dining.notice.model';

export { diningCampaignRequestService };
export { diningCampaignService };
export { diningCategoryService };
export { diningNoticeService };
export { DiningCampaign };
export { DiningCampaignRequest };
export { DiningCategory };
export { DiningtNotice };
